// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewVideo struct {
	ImagePath   string `json:"image_path"`
	Title       string `json:"title"`
	Description string `json:"description"`
	ViewCount   int    `json:"view_count"`
	UploadDate  string `json:"upload_date"`
	VideoPath   string `json:"video_path"`
}

type Video struct {
	ID          string `json:"id"`
	ImagePath   string `json:"image_path"`
	Title       string `json:"title"`
	Description string `json:"description"`
	ViewCount   int    `json:"view_count"`
	UploadDate  string `json:"upload_date"`
	VideoPath   string `json:"video_path"`
}
